### ISSUE TITLE
default value for highlight

### ISSUE THREAD

**Issue by ilan-schemoul** [t-troebst/perfanno.nvim#15]
Hey,
I didn't know 
```
      line_highlights = util.make_bg_highlights("#FF00FF", "#CC3300", 10),
      vt_highlight = util.make_fg_highlight("#CC3300"),
```
were mandatory.
Cause otherwise I just don't see anything so I assumed it was broken until I tried these options.
I think you should put sensible defaults
By the way I tried like the doc said
```
    local util = require("perfanno.util")
    local bgcolor = vim.fn.synIDattr(vim.fn.hlID("Normal"), "bg", "gui")

    require("perfanno").setup({
      line_highlights = util.make_bg_highlights(bgcolor, "#CC3300", 10),
      vt_highlight = util.make_fg_highlight("#CC3300"),
    })
```
but then ...ocal/share/nvim/lazy/perfanno.nvim/lua/perfanno/util.lua:135: Invalid format!

# stacktrace:
  - /perfanno.nvim/lua/perfanno/util.lua:135 _in_ **hex_to_rgb**
  - /perfanno.nvim/lua/perfanno/util.lua:123 _in_ **make_bg_highlights**
  - .config/nvim/lua/plugins/perfanno.lua:8 _in_ **config**
  - .config/nvim/lua/config/lazy.lua:73
  - nvim-main/nvim/init.lua:1

**Comment by t-troebst** [comment]
Yes, the reason why I didn't set anything by default is because I wasn't sure how to reliably get the background color from neovim. That's needed in order to do anything reasonable. And given that my suggested method didn't work for you, it seems like I was right not to make it the default. The installation instructions do mention that you should probably set highlights if you want to use them.

I think using `nvim_get_hl` might be a better way to get the background color and I've updated the instructions to use this instead. However, there is still the fundamental issue that the user might not have set a background color at all. In that case its the terminal background color that matters and there is no reasonable way to get this value at all.

**Comment by t-troebst** [comment]
But I suppose overall it wouldn't be a bad idea to pick *some* colors, even if they end up clashing with the user's color scheme, just to make it obvious that it is working.

**Comment by ilan-schemoul** [comment]
Currently the behaviour is that many users won't read the doc fully or won't get it and think the plugin is broken.

I see three ways

Make it extremely clear in the doc that the value is mandatory and throw an error if the value is not here

Put any color and if the user doesn't like he will anyway pick another one.

Try one the method you described to pick a color and if it fails then catch the error and set a default value.

Any of these ways is reasonable. But I'd strongly suggest against having not doing anything because if users feel like the plugin is broken they'll just be confused and eventually move on.

**Comment by t-troebst** [comment]
Okay I've updated it as follows:

By default it tries to set the background highlights to a 10-step gradient between bgcolor and red. If we can't get the bgcolor then it defaults to black. The default highlight for virtual text is also red.
