### ISSUE TITLE
Minimal example for profiling neovim

### ISSUE THREAD

**Issue by AckslD** [t-troebst/perfanno.nvim#19]
Hi! Do you have a minimal example for how to use this to profile something in neovim? I tried for example
```lua
local func = function()
  print("sleeping")
  vim.system({"sleep", "2"}):wait()
  print("done")
end

vim.cmd.PerfLuaProfileStart()
func()
P(vim.diagnostic.get(0, {}))
vim.cmd.PerfLuaProfileStop()
```
but it didn't show anything (other than the message that "Callgraph has been loaded")

**Comment by t-troebst** [comment]
Once the callgraph is loaded, you can search for hottest lines etc. Try `:PerfHottestLines` (this works best if telescope is installed), annotations should just be on by default.

If you're trying to profile some script, make sure it is saved as a file (i.e. not just in some unnamed buffer) because the luajit profiler gives us filenames to associate the lines with.

**Comment by t-troebst** [comment]
I've had a chance to run your example on my setup and this just doesn't generate any samples to look at. Looks like when you wait on an external command, lua is effectively not running at all and the LuaJIT profiler does not generate any samples. This is not something I have any control over. Here is a minimal example that does something if you want one (although you can also just type `:PerfLuaProfileStart`, type some characters, and type `:PerfLuaProfileStop`):

```lua
local func = function()
  print("sleeping")
  vim.system({"sleep", "2"}):wait()
  print("done")
end

vim.cmd.PerfLuaProfileStart()
func()
P(vim.diagnostic.get(0, {}))
vim.cmd.PerfLuaProfileStop()
```
